[package]
name = "webots-bridge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dora-node-api = "0.3.13"
anyhow = "1.0"
webots-sys = { path = "../webots-sys" }
bytemuck = "1.24.0"
