[package]
name = "planning-op"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dora-node-api = "0.3.13"
anyhow = "1.0"
nalgebra = "0.32" # 强大的矩阵运算库
